/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package produtos_por_ean_menu_e_submenu;

import area_menu_e_submenu.Area_Submenu_01;
import br.com.jmary.home.Home;
import br.com.jmary.utilidades.JOPM;
import categoria_menu_e_submenu.Categoria_Submenu_01;
import conexao_com_banco_de_dados_menu_e_submenu.Conexao_Com_Banco_De_Dados_Submenu_01;
import controle_de_acesso_menu_e_submenu.Controle_De_Acesso_Submenu_01;
import criar_banco_de_dados_menu_e_submenu.Criar_Banco_De_Dados_Submenu_01;
import estabelecimento_menu_e_submenu.Estabelecimento_Submenu_01;
import familia_menu_e_submenu.Familia_Submenu_01;
import home_controle_menus_norte.imagens.Imagens_Menu_Norte;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JMenu;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import login_do_sistema_menu_e_submenu.Login_Do_Sistema_Submenu_01;
import subcategoria_menu_e_submenu.Subcategoria_Submenu_01;
import usuarios_do_sistema_menu_e_submenu.Usuarios_do_Sistema_Submenu_01;

/**
 *
 * @author AnaMariana
 */
public class Produtos_Por_Ean_Menu_01 extends javax.swing.JPanel {
    private static final long serialVersionUID = 1L;
    
    Home Home;
    
    /**
     * Creates new form PnHomeDesigner
     * @param Home2
     */
    public Produtos_Por_Ean_Menu_01( Home Home2 ) {
        initComponents();
        ((BasicInternalFrameUI)Fonema_E_Letra_Frame_Interno.getUI()).setNorthPane(null); //retirar o painel superior 
        
        Home = Home2;
        
        //Habilita troca de seta             
        inicio();
    }
    
    /////////////////////////////////
    URL       imgURL; 
    ImageIcon icon;
            
    URL       imgURL2;
    ImageIcon icon2;
    //////////////////////////////////
    private void inicio(){
        try{                       
            
            imgURL  = Imagens_Menu_Norte.class.getResource("seta_para_baixo.png");
            icon    = new ImageIcon( imgURL );  
            
            imgURL2  = Imagens_Menu_Norte.class.getResource("seta_para_cima.png");
            icon2   = new ImageIcon( imgURL2 ); 
      
            ///SETAR MENU NO HOME//////////////////////////////////////////////
            //Home.Home_Frame_Interno.setJMenuBar( Barra_Menu ); 
            ///////////////////////////////////////////////////////////////////
            
        } catch( Exception e ){ JOPM JOptionPaneMod = new JOPM( 2, "inicio(), \n"
                + e.getMessage() + "\n", this.getClass().getName() ); }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Fonema_E_Letra_Frame_Interno = new javax.swing.JInternalFrame();
        Barra_Menu = new javax.swing.JMenuBar();
        menu_seta = new javax.swing.JMenu();
        menu_ajuda = new javax.swing.JMenu();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        menu_maimais1 = new javax.swing.JMenu();
        jSeparator14 = new javax.swing.JPopupMenu.Separator();
        Produtos_Por_Ean = new javax.swing.JMenuItem();
        jSeparator15 = new javax.swing.JPopupMenu.Separator();
        Familia1 = new javax.swing.JMenuItem();
        jSeparator12 = new javax.swing.JPopupMenu.Separator();
        Subcategoria = new javax.swing.JMenuItem();
        jSeparator11 = new javax.swing.JPopupMenu.Separator();
        Categoria = new javax.swing.JMenuItem();
        jSeparator10 = new javax.swing.JPopupMenu.Separator();
        Area = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        Controle_de_Acesso1 = new javax.swing.JMenuItem();
        jSeparator9 = new javax.swing.JPopupMenu.Separator();
        Controle_de_Acesso = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        jMenuItem8 = new javax.swing.JMenuItem();
        jSeparator8 = new javax.swing.JPopupMenu.Separator();
        jMenuItem5 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem6 = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jMenuItem4 = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        jMenuItem3 = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMenuItem2 = new javax.swing.JMenuItem();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        Fonema_E_Letra_Frame_Interno.setBorder(null);
        Fonema_E_Letra_Frame_Interno.setVisible(true);

        menu_seta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home_controle_menus_norte/imagens/seta_para_cima.png"))); // NOI18N
        menu_seta.setToolTipText("Ocultar Submenu");
        menu_seta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menu_setaMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menu_setaMousePressed(evt);
            }
        });
        Barra_Menu.add(menu_seta);

        menu_ajuda.setText("Ajuda");
        menu_ajuda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menu_ajudaMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menu_ajudaMousePressed(evt);
            }
        });
        menu_ajuda.add(jSeparator3);

        Barra_Menu.add(menu_ajuda);

        menu_maimais1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home_controle_menus_norte/imagens/maismais.gif"))); // NOI18N
        menu_maimais1.setText("++");
        menu_maimais1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menu_maimais1MouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menu_maimais1MousePressed(evt);
            }
        });
        menu_maimais1.add(jSeparator14);

        Produtos_Por_Ean.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home_controle_menus_norte/imagens/iconeCiênciasHumanasPortuguês.png"))); // NOI18N
        Produtos_Por_Ean.setText("Produtos Por Ean");
        Produtos_Por_Ean.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Produtos_Por_EanMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Produtos_Por_EanMousePressed(evt);
            }
        });
        Produtos_Por_Ean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Produtos_Por_EanActionPerformed(evt);
            }
        });
        menu_maimais1.add(Produtos_Por_Ean);
        menu_maimais1.add(jSeparator15);

        Familia1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home_controle_menus_norte/imagens/iconeCompleto.png"))); // NOI18N
        Familia1.setText("Família");
        Familia1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Familia1MouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Familia1MousePressed(evt);
            }
        });
        Familia1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Familia1ActionPerformed(evt);
            }
        });
        menu_maimais1.add(Familia1);
        menu_maimais1.add(jSeparator12);

        Subcategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home_controle_menus_norte/imagens/iconeEnsino Fundamental II.png"))); // NOI18N
        Subcategoria.setText("Subcategoria");
        Subcategoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SubcategoriaMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                SubcategoriaMousePressed(evt);
            }
        });
        Subcategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubcategoriaActionPerformed(evt);
            }
        });
        menu_maimais1.add(Subcategoria);
        menu_maimais1.add(jSeparator11);

        Categoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home_controle_menus_norte/imagens/iconeEnsinoFundamental I.png"))); // NOI18N
        Categoria.setText("Categoria");
        Categoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CategoriaMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CategoriaMousePressed(evt);
            }
        });
        Categoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CategoriaActionPerformed(evt);
            }
        });
        menu_maimais1.add(Categoria);
        menu_maimais1.add(jSeparator10);

        Area.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home_controle_menus_norte/imagens/iconeEnsinoMedio.png"))); // NOI18N
        Area.setText("Área");
        Area.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AreaMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                AreaMousePressed(evt);
            }
        });
        Area.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AreaActionPerformed(evt);
            }
        });
        menu_maimais1.add(Area);
        menu_maimais1.add(jSeparator1);

        Controle_de_Acesso1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home_controle_menus_norte/imagens/foguetemenu.png"))); // NOI18N
        Controle_de_Acesso1.setText("Turbo Flyer");
        Controle_de_Acesso1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Controle_de_Acesso1MouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Controle_de_Acesso1MousePressed(evt);
            }
        });
        Controle_de_Acesso1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Controle_de_Acesso1ActionPerformed(evt);
            }
        });
        menu_maimais1.add(Controle_de_Acesso1);
        menu_maimais1.add(jSeparator9);

        Controle_de_Acesso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home_controle_menus_norte/imagens/semafaro.png"))); // NOI18N
        Controle_de_Acesso.setText("Controle de Acesso");
        Controle_de_Acesso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Controle_de_AcessoMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Controle_de_AcessoMousePressed(evt);
            }
        });
        Controle_de_Acesso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Controle_de_AcessoActionPerformed(evt);
            }
        });
        menu_maimais1.add(Controle_de_Acesso);
        menu_maimais1.add(jSeparator6);

        jMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home_controle_menus_norte/imagens/som.png"))); // NOI18N
        jMenuItem8.setText("Estabelecimento");
        jMenuItem8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jMenuItem8MouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItem8MousePressed(evt);
            }
        });
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        menu_maimais1.add(jMenuItem8);
        menu_maimais1.add(jSeparator8);

        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home_controle_menus_norte/imagens/usuarios.gif"))); // NOI18N
        jMenuItem5.setText("Usuários do Sistema");
        jMenuItem5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jMenuItem5MouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItem5MousePressed(evt);
            }
        });
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        menu_maimais1.add(jMenuItem5);
        menu_maimais1.add(jSeparator2);

        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home_controle_menus_norte/imagens/sql.png"))); // NOI18N
        jMenuItem6.setText("Visualizador de Imagens");
        jMenuItem6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jMenuItem6MouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItem6MousePressed(evt);
            }
        });
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        menu_maimais1.add(jMenuItem6);
        menu_maimais1.add(jSeparator5);

        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home_controle_menus_norte/imagens/ip_conexao.png"))); // NOI18N
        jMenuItem4.setText("Login / Trocar de Usuário");
        jMenuItem4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jMenuItem4MouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItem4MousePressed(evt);
            }
        });
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        menu_maimais1.add(jMenuItem4);
        menu_maimais1.add(jSeparator7);

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home_controle_menus_norte/imagens/conexao.png"))); // NOI18N
        jMenuItem3.setText("Conexão Banco de Dados");
        jMenuItem3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jMenuItem3MouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItem3MousePressed(evt);
            }
        });
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        menu_maimais1.add(jMenuItem3);
        menu_maimais1.add(jSeparator4);

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home_controle_menus_norte/imagens/sql.png"))); // NOI18N
        jMenuItem2.setText("Criar Banco de Dados");
        jMenuItem2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jMenuItem2MouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItem2MousePressed(evt);
            }
        });
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        menu_maimais1.add(jMenuItem2);

        Barra_Menu.add(menu_maimais1);

        Fonema_E_Letra_Frame_Interno.setJMenuBar(Barra_Menu);

        javax.swing.GroupLayout Fonema_E_Letra_Frame_InternoLayout = new javax.swing.GroupLayout(Fonema_E_Letra_Frame_Interno.getContentPane());
        Fonema_E_Letra_Frame_Interno.getContentPane().setLayout(Fonema_E_Letra_Frame_InternoLayout);
        Fonema_E_Letra_Frame_InternoLayout.setHorizontalGroup(
            Fonema_E_Letra_Frame_InternoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 563, Short.MAX_VALUE)
        );
        Fonema_E_Letra_Frame_InternoLayout.setVerticalGroup(
            Fonema_E_Letra_Frame_InternoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fonema_E_Letra_Frame_Interno)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Fonema_E_Letra_Frame_Interno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 79, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void menu_setaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_setaMousePressed
        Home.tocarSon.tocar( 51 );
        tabJanelaSubmenu( this.menu_seta );
    }//GEN-LAST:event_menu_setaMousePressed

    private boolean cimabaixo = true; 
    private void tabJanelaSubmenu( JMenu seta_do_menu ){
        try{

            if( cimabaixo == false ){
                cimabaixo = true;
                
                seta_do_menu.setToolTipText( "Ocultar Submenu" );
                seta_do_menu.setIcon( icon2 );
                
                Home.adicionar_SubMenu( Home.Sub_Menu_Atual );               
                
            } else if( cimabaixo == true ){
                cimabaixo = false;
                                
                seta_do_menu.setToolTipText( "Mostrar Submenu" );
                seta_do_menu.setIcon( icon );

                Home.retirar_SubMenu();                                                 
            }
            
        } catch( Exception e ){ JOPM JOptionPaneMod = new JOPM( 2, "tabJanelaSubmenu, \n"
                + e.getMessage() + "\n", this.getClass().getName() ); }
    }
    
    private void menu_ajudaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_ajudaMousePressed
        //Sistema_Home.adicionarSubmenu(new Submenu2( Sistema_Home ) );     
    }//GEN-LAST:event_menu_ajudaMousePressed

    private void menu_ajudaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_ajudaMouseEntered
        Home.tocarSon.tocar( 51 );
    }//GEN-LAST:event_menu_ajudaMouseEntered

    private void menu_setaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_setaMouseEntered
        Home.tocarSon.tocar( 51 );
    }//GEN-LAST:event_menu_setaMouseEntered

    private void Familia1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Familia1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_Familia1MouseEntered

    private void Familia1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Familia1MousePressed
        Home.tocarSon.tocar( 51 );
        try{

            Home.adicionar_SubMenu(new Familia_Submenu_01( Home ) );

        } catch( Exception e ){ e.printStackTrace(); JOPM JOptionPaneMod = new JOPM( 2, "adicionarSubmenu( Component c ), \n"
            + e.getMessage() + "\n", "Classe: " + "Controle_de_Alterar_Menu_Norte" ); }
    }//GEN-LAST:event_Familia1MousePressed

    private void Familia1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Familia1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Familia1ActionPerformed

    private void SubcategoriaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubcategoriaMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_SubcategoriaMouseEntered

    private void SubcategoriaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubcategoriaMousePressed
        Home.tocarSon.tocar( 51 );
        try{

            Home.adicionar_SubMenu(new Subcategoria_Submenu_01( Home ) );

        } catch( Exception e ){ e.printStackTrace(); JOPM JOptionPaneMod = new JOPM( 2, "adicionarSubmenu( Component c ), \n"
            + e.getMessage() + "\n", "Classe: " + "Controle_de_Alterar_Menu_Norte" ); }
    }//GEN-LAST:event_SubcategoriaMousePressed

    private void SubcategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubcategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SubcategoriaActionPerformed

    private void CategoriaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CategoriaMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_CategoriaMouseEntered

    private void CategoriaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CategoriaMousePressed
        Home.tocarSon.tocar( 51 );
        try{

            Home.adicionar_SubMenu(new Categoria_Submenu_01( Home ) );

        } catch( Exception e ){ e.printStackTrace(); JOPM JOptionPaneMod = new JOPM( 2, "adicionarSubmenu( Component c ), \n"
            + e.getMessage() + "\n", "Classe: " + "Controle_de_Alterar_Menu_Norte" ); }
    }//GEN-LAST:event_CategoriaMousePressed

    private void CategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CategoriaActionPerformed

    }//GEN-LAST:event_CategoriaActionPerformed

    private void AreaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AreaMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_AreaMouseEntered

    private void AreaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AreaMousePressed
        Home.tocarSon.tocar( 51 );
        try{

            Home.adicionar_SubMenu(new Area_Submenu_01( Home ) );

        } catch( Exception e ){ e.printStackTrace(); JOPM JOptionPaneMod = new JOPM( 2, "adicionarSubmenu( Component c ), \n"
            + e.getMessage() + "\n", "Classe: " + "Controle_de_Alterar_Menu_Norte" ); }
    }//GEN-LAST:event_AreaMousePressed

    private void AreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AreaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AreaActionPerformed

    private void Controle_de_Acesso1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Controle_de_Acesso1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_Controle_de_Acesso1MouseEntered

    private void Controle_de_Acesso1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Controle_de_Acesso1MousePressed
        Home.tocarSon.tocar( 51 );
        try{

            //Home.adicionar_SubMenu(new Turbo_Flyer_Submenu_01( Home ) );

        } catch( Exception e ){ e.printStackTrace(); JOPM JOptionPaneMod = new JOPM( 2, "adicionarSubmenu( Component c ), \n"
            + e.getMessage() + "\n", "Classe: " + "Controle_de_Alterar_Menu_Norte" ); }
    }//GEN-LAST:event_Controle_de_Acesso1MousePressed

    private void Controle_de_Acesso1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Controle_de_Acesso1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Controle_de_Acesso1ActionPerformed

    private void Controle_de_AcessoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Controle_de_AcessoMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_Controle_de_AcessoMouseEntered

    private void Controle_de_AcessoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Controle_de_AcessoMousePressed
        Home.tocarSon.tocar( 51 );
        try{

            Home.adicionar_SubMenu(new Controle_De_Acesso_Submenu_01( Home ) );

        } catch( Exception e ){ e.printStackTrace(); JOPM JOptionPaneMod = new JOPM( 2, "adicionarSubmenu( Component c ), \n"
            + e.getMessage() + "\n", "Classe: " + "Controle_de_Alterar_Menu_Norte" ); }
    }//GEN-LAST:event_Controle_de_AcessoMousePressed

    private void Controle_de_AcessoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Controle_de_AcessoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Controle_de_AcessoActionPerformed

    private void jMenuItem8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem8MouseEntered
        Home.tocarSon.tocar( 51 );
    }//GEN-LAST:event_jMenuItem8MouseEntered

    private void jMenuItem8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem8MousePressed
        Home.tocarSon.tocar( 51 );
        try{

            Home.adicionar_SubMenu(new Estabelecimento_Submenu_01( Home ) );

        } catch( Exception e ){ e.printStackTrace(); JOPM JOptionPaneMod = new JOPM( 2, "adicionarSubmenu( Component c ), \n"
            + e.getMessage() + "\n", "Classe: " + "Controle_de_Alterar_Menu_Norte" ); }
    }//GEN-LAST:event_jMenuItem8MousePressed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem5MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5MouseEntered

    private void jMenuItem5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem5MousePressed
        Home.tocarSon.tocar( 51 );
        try{

            Home.adicionar_SubMenu(new Usuarios_do_Sistema_Submenu_01( Home ) );

        } catch( Exception e ){ e.printStackTrace(); JOPM JOptionPaneMod = new JOPM( 2, "adicionarSubmenu( Component c ), \n"
            + e.getMessage() + "\n", "Classe: " + "Controle_de_Alterar_Menu_Norte" ); }
    }//GEN-LAST:event_jMenuItem5MousePressed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem6MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem6MouseEntered

    private void jMenuItem6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem6MousePressed
        Home.tocarSon.tocar( 51 );
        try{

            //Home.adicionar_SubMenu(new Visualizador_Imagens_Submenu_01( Home ) );

        } catch( Exception e ){ e.printStackTrace(); JOPM JOptionPaneMod = new JOPM( 2, "adicionarSubmenu( Component c ), \n"
            + e.getMessage() + "\n", "Classe: " + "Controle_de_Alterar_Menu_Norte" ); }
    }//GEN-LAST:event_jMenuItem6MousePressed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem4MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem4MouseEntered

    private void jMenuItem4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem4MousePressed
        Home.tocarSon.tocar( 51 );
        try{

            Home.adicionar_SubMenu(new Login_Do_Sistema_Submenu_01( Home ) );

        } catch( Exception e ){ e.printStackTrace(); JOPM JOptionPaneMod = new JOPM( 2, "adicionarSubmenu( Component c ), \n"
            + e.getMessage() + "\n", "Classe: " + "Controle_de_Alterar_Menu_Norte" ); }
    }//GEN-LAST:event_jMenuItem4MousePressed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3MouseEntered

    private void jMenuItem3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem3MousePressed
        Home.tocarSon.tocar( 51 );
        try{

            Home.adicionar_SubMenu(new Conexao_Com_Banco_De_Dados_Submenu_01( Home ) );

        } catch( Exception e ){ e.printStackTrace(); JOPM JOptionPaneMod = new JOPM( 2, "adicionarSubmenu( Component c ), \n"
            + e.getMessage() + "\n", "Classe: " + "Controle_de_Alterar_Menu_Norte" ); }
    }//GEN-LAST:event_jMenuItem3MousePressed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2MouseEntered

    private void jMenuItem2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem2MousePressed
        Home.tocarSon.tocar( 51 );
        try{

            Home.adicionar_SubMenu(new Criar_Banco_De_Dados_Submenu_01( Home ) );

        } catch( Exception e ){ e.printStackTrace(); JOPM JOptionPaneMod = new JOPM( 2, "adicionarSubmenu( Component c ), \n"
            + e.getMessage() + "\n", "Classe: " + "Controle_de_Alterar_Menu_Norte" ); }
    }//GEN-LAST:event_jMenuItem2MousePressed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void menu_maimais1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_maimais1MouseEntered
        Home.tocarSon.tocar( 51 );
    }//GEN-LAST:event_menu_maimais1MouseEntered

    private void menu_maimais1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_maimais1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_menu_maimais1MousePressed

    private void Produtos_Por_EanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Produtos_Por_EanMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_Produtos_Por_EanMouseEntered

    private void Produtos_Por_EanMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Produtos_Por_EanMousePressed
        Home.tocarSon.tocar( 51 );
        try{

            Home.adicionar_SubMenu(new Produtos_Por_Ean_Submenu_01( Home ) );

        } catch( Exception e ){ e.printStackTrace(); JOPM JOptionPaneMod = new JOPM( 2, "adicionarSubmenu( Component c ), \n"
            + e.getMessage() + "\n", "Classe: " + "Controle_de_Alterar_Menu_Norte" ); }
    }//GEN-LAST:event_Produtos_Por_EanMousePressed

    private void Produtos_Por_EanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Produtos_Por_EanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Produtos_Por_EanActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Area;
    public javax.swing.JMenuBar Barra_Menu;
    private javax.swing.JMenuItem Categoria;
    private javax.swing.JMenuItem Controle_de_Acesso;
    private javax.swing.JMenuItem Controle_de_Acesso1;
    private javax.swing.JMenuItem Familia1;
    private javax.swing.JInternalFrame Fonema_E_Letra_Frame_Interno;
    private javax.swing.JMenuItem Produtos_Por_Ean;
    private javax.swing.JMenuItem Subcategoria;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator10;
    private javax.swing.JPopupMenu.Separator jSeparator11;
    private javax.swing.JPopupMenu.Separator jSeparator12;
    private javax.swing.JPopupMenu.Separator jSeparator14;
    private javax.swing.JPopupMenu.Separator jSeparator15;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JPopupMenu.Separator jSeparator8;
    private javax.swing.JPopupMenu.Separator jSeparator9;
    private javax.swing.JMenu menu_ajuda;
    private javax.swing.JMenu menu_maimais1;
    private javax.swing.JMenu menu_seta;
    // End of variables declaration//GEN-END:variables
            
}
